yalesites-org/component-library-twig

- components/01-atoms/divider/_divider.scss
- components/01-atoms/divider/divider.stories.js
- package-lock.json
- This is just a cleanup ticket to align the thickness names in the component library with the token names
-
> refactor: updated thickness names to match tokens

- components/01-atoms/lists/_list-item.twig
- components/01-atoms/lists/_list.scss
- components/01-atoms/lists/list.stories.js
- components/01-atoms/lists/list.twig
- components/01-atoms/lists/list.yml
- Initial List component. (to support menus)
- This doesn't currently support nested items. That'll come later if/when needed. The majority of lists are in a wysiwyg, and therefor don't even use this component. Menus do use this, but have their own mechanism for doing nested list items. So this is just to get the basic pieces in place.
> YALB-76: List

- components/00-tokens/breakpoints/_breakpoints.scss
- components/00-tokens/colors/cl-colors.scss
- components/00-tokens/effects/_effects.scss
- components/00-tokens/index.scss
- components/00-tokens/utility/_utility.scss
- components/01-atoms/buttons/_buttons.scss
- components/01-atoms/buttons/button.twig
- components/01-atoms/links/_link.scss
- components/02-molecules/menu/_menu-item.twig
- components/02-molecules/menu/_menu-list.twig
- components/02-molecules/menu/menu-toggle/_menu-toggle.scss
- components/02-molecules/menu/menu-toggle/menu-toggle.js
- components/02-molecules/menu/menu-toggle/menu-toggle.twig
- components/02-molecules/menu/menu.twig
- components/03-organisms/site-header/_site-header.scss
- components/03-organisms/site-header/site-header.stories.js
- components/03-organisms/site-header/site-header.twig
- components/style.scss
- package-lock.json
- package.json
- patches/twig+1.15.4.patch
- [YALB-86: Utility Nav](https://yaleits.atlassian.net/browse/YALB-86) is temporarily blocked by some design discussions, so this PR abstracts some of the "shared" mobile header and menu stuff so that I can work on breadcrumbs and the main menu without being blocked by the utility nav. So, this includes:
- Menu base templates (not demoed anywhere, since they'll be used by each menu, but don't do anything by themselves)
- Mobile Menu toggle
- Updates to the site-header to support mobile designs
> Mobile Header Base

- .storybook/main.js
- package-lock.json
- package.json
- Adds [storybook-addon-html](https://storybook.js.org/addons/@whitespace/storybook-addon-html/) to show rendered HTML markup in Storybook
> feat: add storybook-addon-html

- .storybook/setupTwig.js
- components/02-molecules/menu/menu.twig
- components/02-molecules/page-title/page-title.twig
- components/02-molecules/pop-out-image/_pop-out-image.scss
- components/02-molecules/pop-out-image/pop-out-image.twig
- components/03-organisms/menu/breadcrumbs/breadcrumbs.js
- components/03-organisms/menu/breadcrumbs/breadcrumbs.twig
- components/03-organisms/site-header/_site-header.scss
- components/05-page-examples/_intro-content-examples.twig
- components/05-page-examples/page-examples.stories.js
- components/05-page-examples/standard-page.twig
- package-lock.json
- Adds into content examples to standard page
- Sets the page-title width to "content" width
- Updates tokens to remove "beige" from site-footer color schemes
> YALB-108: Standard Page

- components/01-atoms/images/icons/_icon.twig
- components/02-molecules/accordion/accordion.twig
- components/02-molecules/menu/_menu-item.twig
- components/02-molecules/text-with-image/text-with-image.twig
- components/03-organisms/menu/primary-nav/_primary-nav.scss
- [YALB-250: Wire Text with Media](https://yaleits.atlassian.net/browse/YALB-250)
- [YALB-238: Wire Accordion and Accordion Item](https://yaleits.atlassian.net/browse/YALB-238)
- https://github.com/yalesites-org/yalesites_profile/pull/15
- https://github.com/yalesites-org/atomic/pull/2
- Fixes the main menu link hover color
- Fixes icon path for Drupal
- Fixes the menu nesting for Drupal
- Adds a block to accordion for Drupal's nesting
> YALB-250 and YALB-238: Wiring 2

- components/03-organisms/menu/breadcrumbs/breadcrumbs.twig
- Will not display breadcrumbs if there are only 2 segments. Only if 3 or more levels deep.
> YALB-627: hiding breadcrumbs short trails

- components/02-molecules/menu/_menu-item.twig
- components/02-molecules/menu/menu.twig
- Passes menu__contextual to items so that Drupal uses the right stuff
> YALB-635: Wire Breadcrumbs

- components/03-organisms/menu/breadcrumbs/_yds-breadcrumbs.scss
- components/03-organisms/site-header/_yds-site-header.scss
- Fixes the spacing to make a wider gap above the page title.
> YALB-647: updates page title spacing

- components/02-molecules/tabs/_yds-tab-label.twig
- Removes quotes that break Drupal
> YALB-668: Feedback: First Tab selection on page load

- components/03-organisms/menu/utility-nav/yds-utility-nav.twig
- Adds the ability to show or hide the search box in the utility navigation area
- Note: This requires [PR-120 from yalesites-project](https://github.com/yalesites-org/yalesites-project/pull/120) and [PR-49 from atomic](https://github.com/yalesites-org/atomic/pull/49) to work
> YALB-702: Search: Hide search form

- components/00-tokens/colors/_color-pairings.scss
- components/00-tokens/functions/_map.scss
- components/00-tokens/layout/_layout.scss
- components/02-molecules/banner/action/_yds-action-banner.scss
- components/03-organisms/site-header/_yds-site-header.scss
- components/04-page-layouts/page-layouts.scss
- Updates logic for spacing under header, and above footer
> YALB-562 and YALB-563: Header and Footer spacing

- components/02-molecules/tabs/yds-tabs.twig
- Makes the `role="tablist"` attribute a variable that can be disabled
> YALB-784: Remove aria attribute

- components/02-molecules/alert/yds-alert.js
- fix: alert dismissal wasn't preserved on page refresh if all alerts on a page had not been interacted with.
> fix: alert dismissal wasn't preserved on page refresh if all alerts on a page had not been interacted with

- components/00-tokens/layout/_layout.scss
- components/01-atoms/typography/text/_yds-text.scss
- components/02-molecules/wrapped-image/_yds-wrapped-image.scss
- components/02-molecules/wrapped-image/wrapped-image.stories.js
- components/02-molecules/wrapped-image/yds-wrapped-image.twig
- package-lock.json
- Adds image style - `floated` (default) or `offset`
- Adds image alignment - `left` (default) or `right`
> YALB-789 -  image wrapped variations

- package-lock.json
- Updates `tokens` package to latest version to pull the line-height updates into the latest release branch
- https://deploy-preview-179--dev-component-library-twig.netlify.app/?path=/story/tokens-typography--body-styles (note the line-height changes are in place)
> fix: update to latest tokens release

- components/01-atoms/controls/cta/_yds-cta.scss
- components/01-atoms/forms/textfields/_yds-textfields.scss
- components/02-molecules/search-result/_yds-search-result.scss
- Added padding underneath search page form
- Increases height of text input within search page form
- Before: 
- After:
- Companion PR in atomic: https://github.com/yalesites-org/atomic/pull/79
##Design review
- Figma:
- This branch:
> YALB-913: Bug: Search results page

- components/02-molecules/callout/_yds-callout.scss
- components/02-molecules/cards/custom-card/_yds-custom-card.scss
- fix: `a` element coloring in callouts/cards
- The scope of this ticket was for callouts, but I figured we might as well do the same for custom cards, just in case :+1: 
`<p>Designed for those who intend to pursue graduate and those who wish to <a href="https://google.com">immediately enter a career</a> in which broad scientific training is beneficial.</p>`
> YALB-908 - Bug: Text link style bug for Callout

- components/03-organisms/site-footer/_yds-site-footer.scss
- components/03-organisms/site-footer/yds-site-footer.twig
- Update Privacy Policy link
- Make Yale workmark in the footer as a link
> YALB-888: Feedback: Update Footer links

- components/00-tokens/effects/cl-effects.scss
- components/00-tokens/effects/effects.stories.js
- components/00-tokens/effects/shadows.twig
- components/02-molecules/search-result/_yds-search-result.scss
- components/03-organisms/_list-mixins.scss
- components/03-organisms/menu/primary-nav/_yds-primary-nav.scss
- package-lock.json
- Adds a token for the bottom-only shadow
- Replaces custom box-shadow with the new token for bottom-only shadow in some components
> YALB-844: Capture "bottom-only" shadow as token

- components/03-organisms/card-collection/_yds-card-collection.scss
- When UI cards weren't equal in size, they would be awkwardly aligned. Adding flex box styling has mended this issue.
Before changes:
> YALB-945: CSS issue on News & Event page

- components/01-atoms/controls/button/_yds-button.scss
- fix: focus-visible button styles
> YALB-461 - Link: Focus indicator in Firefox

- components/03-organisms/menu/breadcrumbs/_yds-breadcrumbs.scss
- fix(yalb-974): animate-hidden and z-index on breadcrumbs navigational arrow buttons if [data-scroll-indicator='none']
> YALB-974 - Breadcrumb: Home link broken

- components/02-molecules/menu/_yds-menu-item.twig
- components/03-organisms/menu/primary-nav/_yds-primary-nav.scss
- components/03-organisms/menu/primary-nav/primary-nav.yml
- Add styles for menu links to indicate the active menu trail.
> YALB-933: Menu: Active trail styles

- components/03-organisms/menu/breadcrumbs/_yds-breadcrumbs.scss
- components/04-page-layouts/page-layouts.scss
- components/05-page-examples/events/event-page.twig
- components/05-page-examples/events/events.stories.js
- Add more space between heading and header for pages withouth breadcrumbs
> YALB-1052: Feedback: H1 spacing

- components/02-molecules/accordion/_yds-accordion.scss
- Fixes the property animation for accordion, instead of take in count the `max-weight` property in the trasition, it uses all. The animation was looking good when there were a lot of information in the accordion content, but when the content was short, the animation didn't look smooth, so this fixes.
**** Note: There is a lot of space than expecting between the content and the border, but this is fixed in another PR.
> YALB-1093: Fix accordion animation

- components/03-organisms/galleries/media-grid/yds-media-grid.twig
- Adds darker background for media gallery
> YALB-1095: Add darker background for media gallery

- components/02-molecules/text/yds-text-field.twig
- Adds an available variable for `text_field__base_class` in the `yds-text-field.twig` to get it other base class from `paragraph--text.html.twig` of the `Accordion item` to avoid a margin-bottom because of the class `text-field`.
> YALB-1051: Accordion spacing

- components/02-molecules/alert/_yds-alert.scss
- components/02-molecules/alert/yds-alert.js
- Remove animate mixin on all alerts
- Add dismissal class ```alert__animate``` to handle deliberate animation where needed
- Create ```animatedDismiss``` method to distinguish between dismissed and dismissing
There is a bug with changing the component's controls and the javascript being
re-applied.  @joetower explained how to get around this:
- make a change to the controls
- click another component in the sidebar (maybe just whatever is above or below the component you're working with)
- then click back to the component you were making controls changes on, the change should still be there, but JS will load as it should.
[video example](https://yaleedu.sharepoint.com/sites/YaleSitesUpgradeProgram-ProjectTeam/_layouts/15/stream.aspx?id=%2Fsites%2FYaleSitesUpgradeProgram%2DProjectTeam%2FSha …
> fix(yalb-1094): hidden alert no longer flickers on page load

- components/01-atoms/controls/cta/yds-cta.twig
- components/01-atoms/videos/video-background/yds-video-background.scss
- components/01-atoms/videos/video-background/yds-video-background.twig
- components/02-molecules/banner/grand-hero/_yds-grand-hero.scss
- components/02-molecules/wrapped-image/_yds-wrapped-image.scss
- components/03-organisms/component-wrapper/_yds-component-wrapper.scss
- YALB-1163 - feat: changes the cta component to enable `control__element` from the control component to be passed through the `cta__element` so that we can use the `a` element in Drupal (`control__element: cta__element, cta__element: 'a'` in Atomic).
- YALB-1146 - fix:  `yds-video-background.twig` changes default theme from `gray-800` to `one` so that the video background play/pause button gets the correct background-color.
> YALB-1163 - Create Button Link component

- components/02-molecules/cards/reference-card/event/_yds-event-format.twig
- components/02-molecules/meta/event-meta/yds-event-meta.twig
This PR has linked future PRs for atomic and yalesites-project.
The component was not rendering the format unless it was an array type, although other pieces like storybook had a default that was a string type. This change allows it to reference the 0th element if it's a single element array, or the string text if it was passed.
My only question is: was this not done because an empty string is truthy? So if they pass an empty string, would it think there was a format and display it?
- Allows format check to pass an array or string to allow default storybook value to show
- Allows fallback in format if array doesn't exist to string representation
- No design changes have been made
> fix(YALB-1195): format now displays on string and array

- README.md
Percy was not really being utilized right now, so in an event to keep the workflow for use in the future, changes have been made in the Percy.io site project settings that instead of only auto-approving the `main` branch, we auto-approve all branches.
When reverting this, just change it back to `main`.
- Change Percy.io project settings to auto-approve all branches of component library
- Update documentation to convey to the user that this has been temporarily auto-approved
> chore(YALB-1042): document percy auto-approve

- components/02-molecules/menu/_yds-menu.scss
- Adds the same font weight to the utility nav as the primary nav.
> YALB-1285: fixes utility menu font weights

- components/01-atoms/images/image/_yds-image.scss
- components/02-molecules/tabs/_yds-tabs.scss
- fixes the heading color for headings in the content area of the Tabs block.
> YALB 1282: Bug: Heading color in tab content

- components/01-atoms/images/image/_yds-image.scss
- components/02-molecules/tabs/_yds-tabs.scss
- adds the underline animation to the caption links for image and wrapped image blocks.
> YALB-1277: Fixes animation to link styles

- components/03-organisms/galleries/media-grid/_yds-media-grid-modal.scss
- Fixes the link hover style for media gallery to display as a shade of gray in Drupal.
> YALB-1280: Bug: Media gallery link hover style

- components/02-molecules/meta/event-meta/yds-event-meta.twig
- components/02-molecules/meta/meta.stories.js
- components/05-page-examples/events/events.stories.js
- Change date format of `now` to use unix timestamps over human readable
> YALB-1418: Bug: All events created are showing as past events

- components/02-molecules/alert/_yds-alert.scss
- components/02-molecules/alert/alert.stories.js
- removes `height: 100%`
- Increases `max-height` to `25rem`
- add component theme to the reset button in Storybook 
- Note: we need to set a `max-height` for the alert to be able to be animated. I set it to a large value (`25rem` / `400px`) in hopes that it is large enough. We can adjust this value as needed.
https://github.com/yalesites-org/component-library-twig/assets/366413/c9b7c7d0-7b4f-42ae-9448-1413211f4737
> YALB-1364 - Bug: Alert banner height (FE)

- components/03-organisms/galleries/media-grid/_yds-media-grid-modal.scss
- Adds a `width` to the `svg`s in the media gallery component so that they render in Safari.  
https://github.com/yalesites-org/component-library-twig/assets/366413/63259ec2-a7a6-4a74-bb63-eed430164f73
> YALB-1322 - Bug: Gallery Block - closing x gets cut off (FE)

- components/02-molecules/pull-quote/_yds-pull-quote.scss
> YALB-1290: Bug: Grand Hero Text alignment

- components/02-molecules/banner/action/yds-action-banner.twig
- components/02-molecules/callout/_yds-callout.twig
- components/02-molecules/quick-links/_yds-quick-links--links.twig
- components/02-molecules/wrapped-image/_yds-wrapped-image.scss
- YALB-1272: Bug: Button style inverted
- Fixes button style for `callouts` and `banners`
- This also fixes part of https://yaleits.atlassian.net/browse/YALB-1290
- YALB-905: Links: Inconsistent treatment
- Adds link functionality to `wrapped-image` component
---
https://github.com/yalesites-org/component-library-twig/assets/366413/260b70b2-fe84-415f-b750-151e6c142cd4
> YALB-1272: Bug: Button style inverted | YALB-905: Links: Inconsistent treatment

- components/00-tokens/layout/_layout.scss
- components/01-atoms/divider/cl-dividers.scss
- components/01-atoms/divider/divider.stories.js
- components/01-atoms/forms/textfields/_yds-textfields.scss
- components/01-atoms/typography/headings/_yds-headings.scss
- components/01-atoms/typography/text/_yds-text.scss
- components/01-atoms/videos/video-background/yds-video-background.scss
- components/01-atoms/videos/video-embed/_yds-video-embed.scss
- components/02-molecules/accordion/_yds-accordion.scss
- components/02-molecules/alert/_yds-alert.scss
- components/02-molecules/banner/action/_yds-action-banner.scss
- components/02-molecules/callout/_yds-callout.scss
- components/02-molecules/cards/reference-card/_yds-reference-card.scss
- components/02-molecules/meta/event-meta/_yds-event-meta.scss
- components/02-molecules/quick-links/_yds-quick-links.scss
- components/02-molecules/tabs/_yds-tabs.scss
- components/02-molecules/wrapped-image/_yds-wrapped-image.scss
- components/03-organisms/galleries/media-grid/_yds-media-grid-modal.scss
- components/03-organisms/galleries/media-grid/_yds-media-grid.scss
- components/03-organisms/menu/primary-nav/_yds-primary-nav.scss
- components/03-organisms/site-header/_yds-site-header.scss
- Fixes Safari 14.1 issues: 
- `aspect-ratio` doesn't work in Safari 14.1 | https://caniuse.com/?search=aspect-ratio
- Solution: apply conditional top-padding which equals the aspect-ratio 
- `margin-block` is supposed to work in Safari 14.1, but it wasn't working | https://caniuse.com/?search=margin-block
- Solution: use `margin-block-start` and `margin-block-end`
- this simply replaces a less supported short-hand of the same properties with its long-hand version
- `margin-inline` is supposed to work in Safari 14.1, but it wasn't working | https://caniuse.com/?search=margin-inline
- Solution: use `margin-inline-start` and `margin-inline-end`
- this simply replaces a less supported short-hand of the same properties with its long-hand version
- `padding-block` doesn't work in Safari 14.1 …
> YALB - safari fixes (YALB-1247, YALB-1320, YALB-1323, YALB-1345)

- components/03-organisms/galleries/media-grid/_yds-media-grid.scss
- Adds `width:100%` to `media-grid__image` so that the image fills its parent's width at in-between responsive image sizes
> YALB-1297: Media: Verify images are using optimized styles

- components/02-molecules/page-title/yds-page-title.twig
- Add a 'page_title__display' variable to the page title to switch the display between: 'display', 'hidden', or 'visually-hidden'.
- Display: renders the same code as before without a perceivable change.
- Hidden: No longer renders the page title block.
- Visually Hidden: Adds the class to the block to visually hide using preexisting styles.
- This is tested in the cooresponding upstream PR.
> YALB-1135: Allow title to display as visually hidden

- components/02-molecules/accordion/_yds-accordion.scss
- components/02-molecules/accordion/accordion.stories.js
- components/02-molecules/accordion/yds-accordion.js
- components/02-molecules/accordion/yds-accordion.twig
- Add aria-expanded to toggleAll buttons
- Set initial aria-expanded state on toggleAll button
- Transform the "Expand all" and "Collapse all" to one toggle button
- Replace the first word to Expand or Collapse depending on the current state
- Add css to rotate the icon for visual toggle
- Change "Expand All" to "Collapse All" when all items are manually expanded
- If one or more are not expanded, it will default to "Expand all" unless ALL are expanded
- If all are expanded manually, the toggle will change to "Collapse All"
- Refactor to hopefully better convey what it is doing through method names
> YALB-1445: Accordion collapse and expand features; ARIA state addition

- components/01-atoms/controls/text-link/yds-text-link.js
- components/01-atoms/controls/text-link/yds-text-link.twig
- components/02-molecules/cards/directory-listing-card/_yds-directory-listing-card.scss
- components/02-molecules/cards/directory-listing-card/directory-listing-card.stories.js
- components/02-molecules/cards/directory-listing-card/yds-directory-listing-card.twig
- components/02-molecules/cards/directory-listing-card/yds-directory-listing-card.yml
- components/02-molecules/cards/reference-card/_yds-reference-card.scss
- components/02-molecules/cards/reference-card/examples/_card--examples.twig
- components/02-molecules/cards/reference-card/examples/profile-card.yml
- components/02-molecules/cards/reference-card/reference-card.stories.js
- components/02-molecules/meta/meta.stories.js
- components/02-molecules/meta/profile-meta/_yds-profile-meta.scss
- components/02-molecules/meta/profile-meta/yds-profile-meta.twig
- components/02-molecules/molecules.scss
- components/03-organisms/_grid-mixins.scss
- components/03-organisms/block-wrapper/_yds-block-wrapper.scss
- components/03-organisms/block-wrapper/block-wrapper.stories.js
- components/03-organisms/block-wrapper/yds-block-wrapper.twig
- components/03-organisms/card-collection/_yds-card-collection.scss
- components/03-organisms/card-collection/card-collection.stories.js
- components/03-organisms/card-collection/yds-card-collection.twig
- components/03-organisms/organisms.scss
- components/05-page-examples/events/events.stories.js
- components/05-page-examples/profiles/profile.twig
- components/05-page-examples/profiles/profiles.stories.js
- Adds new meta component for profiles
- Adds new display mode: `condensed` for `news`, `events`, `profiles`
- Adds new `directory-listing` display mode for `profiles`
https://github.com/yalesites-org/component-library-twig/assets/366413/efa0a81e-5c63-4016-a16f-a27f252ab974
---
https://github.com/yalesites-org/component-library-twig/assets/366413/15a66438-3d4a-435b-9673-bf2d9cb31eee
> YALB-1440: Create and theme profile-meta component (FE) | YALB-1436: Create new display modes (FE)

- components/02-molecules/cards/directory-listing-card/directory-listing-card.stories.js
- components/02-molecules/cards/reference-card/_yds-reference-card.scss
- components/02-molecules/cards/reference-card/examples/_card--examples.twig
- components/02-molecules/cards/reference-card/reference-card.stories.js
- components/03-organisms/card-collection/_yds-card-collection.scss
- components/03-organisms/card-collection/card-collection.stories.js
- components/03-organisms/card-collection/yds-card-collection.twig
- components/05-page-examples/_intro-content-examples.twig
- components/05-page-examples/events/_event-collection--example.twig
- components/05-page-examples/post/post-article.twig
- components/05-page-examples/standard-pages/standard-page-with-banner-left-align.twig
- components/05-page-examples/standard-pages/standard-page-with-banner.twig
- Updates card collection: `[data-collection-type='profile-directory'] flex-align: start`
- Renames `card_example_type` to `card_collection__source_type`
> YALB-1478: Views: display modes and dynamic lists

- components/01-atoms/lists/_yds-list-item.twig
- components/01-atoms/lists/list.yml
- components/01-atoms/lists/yds-list.twig
- components/02-molecules/menu/_yds-menu-item.twig
- components/02-molecules/menu/_yds-menu-list.twig
- components/03-organisms/menu/primary-nav/_yds-primary-nav.scss
- components/03-organisms/menu/primary-nav/primary-nav.yml
- Adds option list_heading to the main menu 
- or by navigating to: https://pr-408-yalesites-platform.pantheonsite.io/welcome and expanding any menu item.
> YALB 1511 - Theming Primary Navigation Headings

- components/02-molecules/banner/action/yds-action-banner.twig
- components/02-molecules/banner/grand-hero/yds-grand-hero.twig
- Adds variables to wire heading__level to Drupal field
- Keeps default set to `2`
> YALB-1215: Dials: Banner heading levels

- package-lock.json
- package.json
- webpack/plugins.js
- webpack/webpack.common.js
- Fontawesome fonts in the `/fonts` directory of the repo are not being included in releases
`npm ci`
`npm run build`
> YALB-1559: Bug: fontawesome fonts included in multidevs but not releases

- components/02-molecules/banner/action/_yds-action-banner.scss
- components/02-molecules/banner/action/yds-action-banner.twig
- components/02-molecules/banner/grand-hero/_yds-grand-hero.scss
- components/02-molecules/banner/grand-hero/yds-grand-hero.twig
- Moves component theme to root div of the following components:
- Grand Hero
- Action Banner
> YALB-1410: Bug: Accessibility (FE)- Color Contrast issues in automatic testing tools

- components/01-atoms/controls/text-link/_yds-text-link.scss
- components/02-molecules/link-skip/_yds-link-skip.scss
- components/02-molecules/link-skip/link-skip.stories.js
- components/02-molecules/link-skip/link-skip.yml
- components/02-molecules/link-skip/yds-link-skip.twig
- components/02-molecules/molecules.scss
- Adds a component for `link skip`: 
- Wires new link skip to `html.html` template.
- Fixes chosen input search colors on `admin/content` tags
> YALB-1527 - Bug: Update link styling "Skip to Main Content" | YALB-1560 - Blank space in toolbar on admin theme

- components/00-tokens/spacing/spacing.twig
- components/01-atoms/forms/select/_yds-select.scss
- components/02-molecules/cards/custom-card/_yds-custom-card.scss
- components/03-organisms/menu/primary-nav/_yds-primary-nav.scss
- package-lock.json
- Reverts blue color values in the "Old Blues" theme and "One" theme in "Component Themes" back to original `medium` and `light` blues, and `gray 100` `gray 800`. 
https://github.com/yalesites-org/component-library-twig/assets/366413/c8bf7b16-d4fd-41c0-95c2-2cb985f3da13
> YALB-1562 themes previous old blues

- components/02-molecules/cards/reference-card/_yds-reference-card.scss
- components/02-molecules/meta/profile-meta/_yds-profile-meta.scss
- adds correct aspect-ratio for profile card grid - 1/1
- fixes safari rendering bug
https://github.com/yalesites-org/component-library-twig/assets/366413/b878f783-ed84-49fa-b8f2-9320e850c404
---
https://github.com/yalesites-org/component-library-twig/assets/366413/46fd6c2d-ecf0-4949-8b96-d656807d1124
> fix(YALB-1622): fix aspect-ratio for profile card grid

- components/02-molecules/menu/_yds-menu-item.twig
Resulting work can be seeing at [YaleSites PR multidev](https://github.com/yalesites-org/yalesites-project/pull/525)
- Uses `node_title` in basic menu for first submenu item (mimics mega menu, but for basic)
> YALB-1685: Bug: Error when going to "Manage Settings" on certain pages

- components/02-molecules/cards/directory-listing-card/_yds-directory-listing-card.scss
- components/02-molecules/cards/directory-listing-card/yds-directory-listing-card.twig
- Replaces the text-based email address with a `mailto: link value` link with `Email` text
- Atomic PR: https://github.com/yalesites-org/atomic/pull/203
https://github.com/yalesites-org/component-library-twig/assets/366413/7b379634-ccce-4439-b6c8-ee4df5a3d647
> YSP-275: Long email breaks Profile card grid: update email address to linked mailto

- components/02-molecules/content-spotlight-portrait/yds-content-spotlight-portrait.twig
- components/02-molecules/text-with-image/yds-text-with-image.twig
- Wraps headings in conditional
https://github.com/yalesites-org/component-library-twig/assets/366413/d58de1d5-dfe8-463c-9afa-4c104dc6a85f
> YSP-277: Spotlight without header shows an empty h tag

- components/01-atoms/controls/text-link/_yds-text-link.scss
- Adds CSS to footer links to have shadow color matching background color
> YSP-353: Release Bug: Footer link style

- components/02-molecules/page-title/_yds-page-title.scss
- components/05-page-examples/standard-pages/standard-page.stories.js
- components/05-page-examples/standard-pages/standard-page.twig
The issue was when hiding the page title, yet creating a block that contained a header for its first element, it would cause the header item to bleed into the breadcrumbs.  This was due to the visually hidden happening on the whole div.  In normal cases, the heading has a margin-top of 1em due to text-field-header-spacing on the h1.  We emulate this by targeting the div that still is present containing the visually hidden page title so that we still have the same spacing.
- Add margin-tops to both visually-hidden page titles and hidden page titles
- Add a storybook variable to display these in a standard page
> YSP-323: breadcrumb overlayed into text block with heading when page title hidden

- components/02-molecules/menu/menu-toggle/yds-menu-toggle.js
- components/03-organisms/site-header/_yds-site-header.scss
- components/03-organisms/site-header/yds-site-header.twig
When resizing the window to a mobile size, the closed menu actually shows temporarily and then animates up to hide itself.
A loaded menu state is one where the page has been loaded, but no toggles have been made.  This lets us take that into account and not display the visual rollup on a resize.
- Add `loaded` initial menu state so that we can properly hide the menu on initial resize
- On window resize, set the state to `loaded` if it was `closed`
> YSP-352: Mobile menu hide animation on resize

- lib/ys_link/config.js
The mega footer allows images to be linked, which could be external, causing the external link to occur in some cases, which looks odd.  This skips those and any that would contain an image inside of the link since it would look odd in most cases I can think of.
- Excludes link treatment for links containing an image tag
> YSP-426: Placement for the external link icon on footer logo

- components/01-atoms/images/image/_image.twig
- components/03-organisms/galleries/media-grid/_yds-media-grid.scss
- components/03-organisms/galleries/media-grid/media-grid.yml
- Adds "Missing image" for images with no src
- Ensure the text that is displayed has good contrast on the black background
- Create an instance in Storybook showing off a no-image gallery item
> YSP-375: TwigTweak errors when removing media used in gallery

- components/02-molecules/cards/custom-card/_yds-custom-card.scss
- components/02-molecules/cards/directory-listing-card/_yds-directory-listing-card.scss
- components/02-molecules/cards/reference-card/_yds-reference-card.scss
- Adds conditional logic to `reference__card__overline` in Atomic template: 
- Adds `bottom-margin` to `__image` s in card grid to create more space between the image and the heading
- The ticket issue highlighted `page` grid items, specifically, but this fix applies to all card grid type items. 
https://github.com/yalesites-org/component-library-twig/assets/366413/3e9af43b-6b8b-48b6-9d7f-869db358255c
> YSP-366: Card display mode spacing between heading, content, and image

- components/02-molecules/cards/reference-card/_yds-reference-card.scss
In single card types like reference cards, the hover link and link would change color, which does not match Storybook, which keeps the text white, even when visited.  This attempts to get us closer to a consistent look with Storybook.
- Modifies what `--color-link-hover` is in the case of the heading link on a reference card to match color-link-hover
- This mimics what grand hero is doing in a similar case
- Verify these in Safari, Firefox, and a Chromium-based browser as they had different behaviors
> fix(YSP-527): V1.3.0: Reference Card link color contrast

- components/02-molecules/quick-links/_yds-quick-links.scss
- components/02-molecules/quick-links/quick-links.stories.js
- components/02-molecules/quick-links/yds-quick-links.twig
- Remove the entire 'variation' control, there are no variations now.
- Remove any styles related to 'subtle', variations were removed.
- Remove any custom code related to the 'subtle' variation.
> YSP-519: Tech debt - remove subtle quicklinks from component library

- components/02-molecules/embed/_yds-embed.scss
- components/02-molecules/embed/embed.stories.js
- [Yalesites Project: PR #662](https://github.com/yalesites-org/yalesites-project/pull/662)
- Adds MS forms embed example to storybook
- Updated forms embedType height to be `90vh`
> YSP-541: Embed: Add Microsoft Forms

- components/02-molecules/alert/yds-alert.twig
- components/02-molecules/inline-message/_yds-inline-message.scss
- components/02-molecules/inline-message/inline-message.stories.js
- components/02-molecules/inline-message/yds-inline-message.twig
- components/02-molecules/molecules.scss
- Adds new component for In-Line Message
> YSP-335: New block: In-Line Message

- components/01-atoms/videos/video-background/yds-video-background.twig
- Adds `playsinline` to video tag in adherence to Safari's newer policies
- Keep in mind you must not be in low power mode for this to be successful
- Video should be on grand hero on front page
> YSP-604: Grand Hero Video doesn't load on mobile

- components/01-atoms/date-time/yds-date-time.twig
- components/02-molecules/meta/event-meta/event-localist.yml
- components/02-molecules/meta/event-meta/yds-event-meta-localist.twig
- Updated start and end date formatted
- Updated start and end time formatted
- Delete comma and change "to" to "-"
> YSP-583: Event date display a range

- components/01-atoms/forms/_yds-form.scss
Change the "four" (subtle) webform button color theme to mimic the opposite of "five" (deep).  When using subtle it resulted in a very bad contrast to the point where people thought the button was disabled, which it is not.
- Attempts for the webform submit button using Button theme 4 to mimic the opposite of theme 5 (Deep)
- Creates a border around it to give it definition
> YSP-625: Submit button color looks disabled when it is not

- components/02-molecules/meta/event-meta/event-localist.yml
- components/02-molecules/meta/event-meta/yds-event-meta-localist.twig
By not having the date with the formatted time, it's impossible for the date formatter to know how to format based on daylight savings time or not.  By having the full UTC time, it can do this properly.
Work also done in [yalesites-project](https://github.com/yalesites-org/yalesites-project/pull/744)
- Passes the UTC `datetime` for the start and end to the twig file for more formatting to occur
> YSP-649: EDT vs EST from Localist causing incorrect time render

- components/02-molecules/content-spotlight-portrait/yds-content-spotlight-portrait.twig
- components/02-molecules/text-with-image/yds-text-with-image.twig
- Adds support for passing heading level through for spotlights
> YSP-670: Spotlights provide H2 in Banner Section

- components/02-molecules/banner/banner.stories.js
- components/02-molecules/banner/image/yds-image-banner.scss
- components/02-molecules/banner/image/yds-image-banner.twig
- components/02-molecules/molecules.scss
- [YaleSites Project](https://github.com/yalesites-org/yalesites-project/pull/770)
- [Atomic](https://github.com/yalesites-org/atomic/pull/270)
- Adds size dial to image banner controls (tall and short)
- Mimic grand hero twig and SCSS to give similar experience and expectations
> YSP-680: PRESIDENT: Add dial to image banner to allow default and large image display

- .storybook/preview.js
- components/_settings/config.stories.js
- lib/link-treatment/link-treatment.scss
- Uses `args` in config story
- Create way to use localStorage with a default fallback on values
- Remove "Save" feature when updating stories
- Use `@use` over `@import` for `link-treatment.scss`
- Remove `console.log` message
- Defined `resetAttributes` to the window object so we don't get redefinition errors
> YSP-752: Storybook global config settings don't use localStorage any longer

- components/02-molecules/link-grid/_yds-link-grid.scss
- components/03-organisms/layout/layout.stories.js
- components/03-organisms/layout/layout/_layout--example.twig
- components/03-organisms/layout/layout/_yds-layout.scss
- Adds Link Grid component to the layout fifty-fifty option
- The Layout acceptance criteria for allowed components is as follows: 
- Fifty-Fifty
- Text
- Accordion
- Media
- Link Grid
- Thirty-Thirty-Thirty
- Text
- Media
> IYY-301: Add Link Grid component as an option in the new 1/2-1/2 layout

- .github/pull_request_template.md
The previous Figma URL was out of date, so this points now to the latest UI Kit version.  Since we also are not using Percy, I removed that as well, and we can re-add it if we decide to re-activate it in the CI.
- Updates Figma URL to latest in PR template
- Removes Percy reference from PR template
> Update Git PR Template Figma URL and remove Percy reference

- components/01-atoms/lists/_yds-list.scss
- components/02-molecules/cards/reference-card/reference-card.stories.js
- Adds styling for reference card categories to mimic the directory listing overline
- Cleans up Storybook to function a bit better for users
> YSP-768: Update category styling on reference cards

- components/02-molecules/cards/custom-card/_yds-custom-card.scss
- ~~Causes screen sizes smaller than `tokens.$break-s` to mimic full desktop mode to have image over the content instead of beside it.~~
- Make `flex` the default to allow the image to always appear above the content for a custom card.
> YSP-564: Custom Cards on mobile responsiveness

- components/02-molecules/link-group/_yds-link-group.scss
- components/03-organisms/site-footer/_site-footer-mega.twig
- components/03-organisms/site-footer/_yds-site-footer.scss
- components/03-organisms/site-footer/site-footer.stories.js
- Fixes contrast issues for footer content links in multiple states
- Fixes footer link group contrast issues in multiple themes
> YSP-785: A11y: New Haven Green + ONHA Mega Footer link contrast

- components/00-tokens/layout/_layout.scss
- components/02-molecules/banner/banner.stories.js
- components/02-molecules/banner/video/yds-video-banner.scss
- components/02-molecules/banner/video/yds-video-banner.twig
- components/02-molecules/molecules.scss
- Adds new Video Banner component
- Allows for changing the width in a dial
https://github.com/user-attachments/assets/6a1e249b-6a61-4b56-aeb7-a67ddae1c46d
> IYY-327: Support Video Embed on Image Banner

- components/02-molecules/taxonomy-display/_yds-taxonomy-display--links.twig
- components/02-molecules/taxonomy-display/_yds-taxonomy-display.scss
- components/02-molecules/taxonomy-display/taxonomy-display.stories.js
- components/02-molecules/taxonomy-display/taxonomy-display.yml
- components/02-molecules/taxonomy-display/yds-taxonomy-display.twig
- Added condition to check if taxonomy_display__item__terms is empty and display 'None' text if true.
- Updated SCSS to add styles for empty state and adjust padding.
- Removed redundant condition in yds-taxonomy-display.twig to always show the taxonomy display container.
> Feedback v1.13.0-1: Add empty state and style updates to taxonomy display

- components/02-molecules/meta/event-meta/yds-event-meta-localist.twig
- components/02-molecules/meta/meta.stories.js
- components/04-page-layouts/cl-page-args.js
Work also completed in [Yalesites Project](https://github.com/yalesites-org/yalesites-project/pull/901)
- Introduced `event_meta__with_calendar` to conditionally display the "Add to Calendar" button.
- Updated `meta.stories.js` to include `withCalendar` argument and default value.
> Hotfix: v1.13.0: Add conditional calendar button

- components/03-organisms/site-header/yds-site-header.twig
- Hides the hamburger menu if there are no items in the main and utility menus.
- [  ] Delete or disable all menu items in both menus, verify you cannot see the hamburger menu
- [  ] Enable at least one menu item in either menu, verify you can see the hamburger menu.
> YSP-738 :: Reimplement hiding hamburger menu if no menu items exist

- components/02-molecules/cards/reference-card/yds-reference-card.twig
- components/02-molecules/meta/event-meta/event-localist.yml
- components/02-molecules/meta/event-meta/yds-event-meta-localist.twig
- components/02-molecules/meta/meta.stories.js
- components/04-page-layouts/cl-page-args.js
More work done at [YaleSites Project](https://github.com/yalesites-org/yalesites-project/pull/908)
- Indicated past events in event meta by adding a conditional check to display "Past Event:" for dates that have already passed.
- Added `is_passed_event` flag to each event date in `event-localist.yml`.
- Included `event_featured_date` with `is_passed_event` flag.
- Updated `yds-event-meta-localist.twig` to check `is_passed_event` flag for determining if an event has passed.
- Updated event date rendering logic by adding a fallback to the old way of rendering if `event_featured_date` is not passed.
- Replaced `event_dates.0` with `event_featured_date` for date comparisons and rendering.
- Changed "Show More Dates" to "Show All Dates" and "Hide More Dates" to "Hide All Dates".
- Fix …
> YSP-844: Event Meta Block Date Visibility Improvements

- components/02-molecules/text-with-image/_yds-text-with-image.scss
- components/02-molecules/text-with-image/text-with-image.stories.js
- components/02-molecules/text-with-image/yds-text-with-image.twig
- add style option to text-with-image
- add imageStyle prop to stories
- add offset image style variations
> YSP-370: Add Offset/Inline Design Options to Landscape Spotlight Block

- components/01-atoms/controls/control.stories.js
- components/01-atoms/controls/cta/_yds-cta-examples.twig
- components/01-atoms/controls/cta/_yds-cta.scss
- components/01-atoms/divider/_yds-divider.scss
- components/01-atoms/divider/divider.stories.js
- components/01-atoms/forms/_yds-form.scss
- components/01-atoms/forms/contact-form-example.twig
- components/01-atoms/forms/forms.stories.js
- components/01-atoms/forms/textfields/_yds-textfields.scss
- components/02-molecules/accordion/_yds-accordion.scss
- components/02-molecules/accordion/accordion.stories.js
- components/02-molecules/cards/reference-card/_yds-reference-card.scss
- components/02-molecules/link-grid/_yds-link-grid.scss
- components/02-molecules/pull-quote/_yds-pull-quote.scss
- components/02-molecules/pull-quote/pull-quote.stories.js
- components/02-molecules/tabs/_yds-tabs.scss
- components/02-molecules/tabs/tabs.stories.js
- components/03-organisms/layout/layout/_yds-layout.scss
- Tabs: Transparent tab buttons on dark backgrounds and improved text contrast.
- Pre-built Forms: Adjusted input background colors and fixed asterisk color for visibility.
- Quote: Dynamically adjusted text color based on section background.
- Divider: Updated color to adapt to section background.
- Button: Colors adjusted for proper contrast with section backgrounds.
- Accordion: Applied color adjustments similar to tabs.
- Reference Card: Repositioned text area for better text width and layout.
- [YaleSites Project](https://github.com/yalesites-org/yalesites-project/pull/898)
- [Atomic](https://github.com/yalesites-org/atomic/pull/331)
> YSP-761 :: Add available blocks to regions for new layouts

- components/02-molecules/banner/banner.stories.js
- components/02-molecules/banner/grand-hero/_yds-grand-hero.scss
- components/02-molecules/banner/grand-hero/yds-grand-hero.twig
- Adds option to block: Floating Box Narrow 
Note that the "contained" option has a label of "Floating Box", so I added another with the key "contained-narrow" for which the label is "Floating Box Narrow"
> YSP-716 :: Add "Contained Narrow" Design Option to Grand Hero Block

- components/02-molecules/cards/reference-card/_yds-reference-card.scss
- components/02-molecules/cards/reference-card/examples/page-card.yml
- components/02-molecules/cards/reference-card/reference-card.stories.js
- Updated the grid-column property for the reference card to improve layout alignment in two-column configurations, restoring the previously used alignment for single column configurations. Added a specific rule for `.yds-two-column` to ensure proper positioning/overriding.
> YSP-589: Add Page Content Type Support to Reference Card Block

- components/02-molecules/pull-quote/_yds-pull-quote.scss
- Added a specific rule to reset the left margin to 0rem for pull quotes inside the `.yds-two-column` container. This ensures proper alignment in two-column layouts while maintaining the default margin elsewhere.
> YSP-874: Quote Block 'Bar Right' Style Alignment Issues in Narrow Sections

- components/02-molecules/pull-quote/_yds-pull-quote.scss
- components/02-molecules/pull-quote/pull-quote.stories.js
- Updated the accent color for the 'one' theme in the pull-quote component to use `--color-slot-two` instead of `--color-slot-one` only when inside of section layout `one`. This allows the same color to not be on top of each other.
> YSP-882: Quote styling doesn't adapt to section background colors

- components/03-organisms/menu/breadcrumbs/breadcrumbs.stories.js
- components/03-organisms/menu/breadcrumbs/yds-breadcrumbs.twig
- Add breadcrumb depth functionality
- [Atomic](https://github.com/yalesites-org/atomic/pull/330)
> IYY-345: Breadcrumbs at level 2 instead of level 3

- components/02-molecules/page-title/_yds-page-title.scss
- components/03-organisms/layout/two-column/_yds-two-column.scss
- components/03-organisms/menu/breadcrumbs/_yds-breadcrumbs.scss
- components/04-page-layouts/page-layouts.scss
- Adjusts css for layout--banner content, breadcrumbs, and title
- Remove two-column top margin on first element in the 70%
> YSP-803: Reduce Excessive Padding Between Breadcrumbs and Banner Blocks

- components/01-atoms/tables/_table.scss
- [Atomic](https://github.com/yalesites-org/atomic/pull/346)
- [Multidev](https://github.com/yalesites-org/yalesites-project/pull/952)
- Added text color for table rows and headers to enhance readability. The changes include:
- Setting text color to black for even rows.
- Setting text color to black for table headers.
> YSP-875: Text: Tables in a section have a color contrast issue

- components/03-organisms/menu/secondary-nav/_yds-secondary-nav.scss
- Added styles to target elements with class ending in `nav__item--active`.
- Updated `secondary-nav__toggle--with-sub` to include a border-bottom when its parent contains an active nav item.
- Adjusted `secondary-nav__link--level-0` to use border-bottom for underline treatment instead of text-decoration.
> YSP-892: Design treatment for active Content Collect parent menu items

- components/03-organisms/menu/secondary-nav/_yds-secondary-nav.scss
- components/03-organisms/site-in-this-section/_site-in-this-section.scss
- components/03-organisms/site-in-this-section/yds-site-in-this-section.js
- Removes underline decoration of selected parent content collection menu item
- Left aligns content collection menu to match rest of content
- Update javascript to reflect this change in left alignment since it creates a negative margin, allowing the arrow to appear at the right time
- Work also done in [Atomic](https://github.com/yalesites-org/atomic/pull/349)
> YSP-892: Design treatment for active Content Collection parent menu items and location move

- components/03-organisms/site-in-this-section/yds-site-in-this-section.twig
- Replace 'aria-hidden' and 'tabindex' attributes with 'aria-label' to enhance accessibility for navigation controls.
> YSP-896: Accessibility: Secondary scroll arrows unlabeled

- components/03-organisms/layout/layout.stories.js
- components/03-organisms/layout/layout/_yds-layout.scss
- components/03-organisms/layout/layout/yds-layout.twig
- components/03-organisms/layout/two-column/_yds-two-column.scss
- Implement padding_options for layout component
- [Yalesites Project](https://github.com/yalesites-org/yalesites-project/pull/938)
> YSP-863 :: Add Section Padding Options

- components/02-molecules/banner/grand-hero/_yds-grand-hero.scss
- components/02-molecules/banner/grand-hero/yds-grand-hero.twig
- Adds ability to replace Grand Hero heading with a PNG
> LIB: ST-Overlay-PNG

- components/01-atoms/tables/_table.scss
- components/01-atoms/tables/example-tables.twig
- components/01-atoms/tables/table.js
- components/01-atoms/tables/table.stories.js
- Applies styling to a table within a section that has a background.
- [Atomic](https://github.com/yalesites-org/atomic/pull/347)
> IYY-385 :: Table stylign in two columns with a background color

- components/02-molecules/page-title/yds-page-title.twig
- components/05-page-examples/post/post-article.twig
- components/05-page-examples/post/post.stories.js
- Renames `page_title__show_social_links` to `page_title__show_social_media_sharing_links`
- Defaults a `NULL` value of this to `FALSE`
- Add control to storybook to see the effect of changing this value
- Made appropriate [YaleSites Project](https://github.com/yalesites-org/yalesites-project/pull/971) changes to enable this to happen in Drupal
> YSP-912: Change default for social media sharing on Post content type

- components/01-atoms/tables/_table.scss
While this originally worked for tables inside of sections, it did not work for layout builder tables created due to sub-item paragraphs.  This scopes it so that this still works for sections while allowing layout builder to not take on the new look.  We also adjusted this on the `move` functionality table, and made the weight link easier to read.
- Nested table styles under `.yds-layout` to scope specific styles.
- Removed unused dark mode hover and focus styles for `.table-wrapper`.
- Ensured consistent background and color handling for table rows.
- Ensured consistent background and color handling for `Move` table in Drupal when moving blocks
- Ensured weight toggle is easier to read when in the `Move` table
> YSP-928: Layout Builder Block Tables in Dark Mode Unreadable

- components/03-organisms/menu/breadcrumbs/breadcrumbs.stories.js
- components/03-organisms/menu/breadcrumbs/yds-breadcrumbs.twig
- Removed the logic that sliced the breadcrumbs items array based on `breadcrumbs__trail_level`.
- Work also done in [Atomic](https://github.com/yalesites-org/atomic/pull/361)
> Hotfix: YSP-951: Breadcrumbs not showing more than 2 trails levels

- components/02-molecules/cards/reference-card/reference-card.stories.js
- components/02-molecules/cards/reference-card/yds-reference-card.twig
- Changes the reference_card__image property (which corresponds to 'withImage' in js files) to be set using the show_thumbnails property from ys_views_basic so that the show_thumbnail is no longer required in the component. 
Note: In the twig file, there were two properties being set to control the image display: reference_card__image and show_thumbnail. I have updated it so that it only uses reference_card__image which is set by 'Show Teaser Image' or 'withImage' if in Storybook, and is by default set to 'true' (the canonical node, Featured Card block).
Uses Atomic branch: https://github.com/yalesites-org/atomic/pull/332
> YSP-814 :: Remove `Show Thumbnails` in reference card to use `with-image`

- components/02-molecules/cards/custom-card/_yds-custom-card.scss
- components/03-organisms/layout/layout/_yds-layout.scss
- components/03-organisms/menu/breadcrumbs/_yds-breadcrumbs.scss
- Increased bottom margin of card headings for improved visual separation and alignment with design guidelines.
- Added top and bottom margin to layout dividers when parent components have no padding, ensuring consistent spacing.
- Introduced bottom padding to the breadcrumbs container using spacing tokens for better separation from following content and enhanced layout consistency.
> YSP-960: OPAC Fixes - Improve Component Spacing for Better Visual Hierarchy

- components/00-tokens/typography/_typography.scss
- components/01-atoms/controls/text-link/_yds-text-link.scss
The Office of Public Affairs and Communications requested changes to Mallory heading typography to improve visual hierarchy. Updated the heading mixin to default to Book weight (400) instead of Medium weight (500) for all Mallory headings (H1-H6).
This change ensures Mallory headings appear with the lighter Book weight while maintaining the existing component architecture and backward compatibility.
- Modified heading mixin logic to use Book weight as default for Mallory headings
- Added explicit 'medium' parameter for backward compatibility
- Added detailed comments documenting the change from old to new behavior
- YaleNew headings remain completely unaffected
- Other Medium weight text across the site remains unchanged
- Other work done in …
> YSP-1073: Update Mallory heading typography styling - change weight and reduce size

- components/02-molecules/pager/yds-pager.twig
- Changed the pager labels to improve a11y experience:
- "Page" to "Go to"
- "Current page" to "Current"
- "Previous page" to "Previous"
- "Next page" to "Next"
> YSP-1069: Update pager aria page label text for clarity

- components/03-organisms/menu/primary-nav/_yds-primary-nav.scss
The "Explore <page title>" link in the mega menu was incorrectly switching to YaleNew font when the global font setting was set to YaleNew. This element should always display in Mallory font regardless of global settings.
Removed conflicting @include tokens.heading(h6) declaration that was overriding the intended navigation font styling. The explore bar link now relies solely on the font: var(--font-style-nav-primary-1) CSS variable which provides consistent Mallory styling.
This ensures proper visual hierarchy and maintains design consistency in the mega menu navigation component.
- Forces `Explore` link to always be Mallory font
> Hotfix: YSP-1086: Mega Menu "Explore" Font Change

- components/01-atoms/controls/cta/_yds-cta.scss
- components/02-molecules/banner/action/_yds-action-banner.scss
- Removed temporary theme-specific hover color overrides in CTA SCSS that were used as a workaround.
- Fixed typo on action banner secondary color variable.
> YSP-1113: Action banner CTA color contrast

- components/03-organisms/site-in-this-section/_site-in-this-section.scss
- Reduced the z-index of the section navigation menu from 2 to 1 to resolve potential stacking context issues with primary nav.
> YSP-1112: Mobile Navigation Menu Appears Behind Content Collection

- components/02-molecules/embed/_yds-embed.scss
- components/02-molecules/embed/embed.stories.js
- Added a new story, EmbedGoogleCalendar, to demonstrate embedding a Google Calendar using the embedTwig component. Configured with example calendar URL, title, and default args.
- Other work completed in https://github.com/yalesites-org/yalesites-project/pull/1048
> YSP-1039: Embed: Google Calendar

- package-lock.json
- Actually use the latest tokens version
> YSP-1141: RC: AI Palette missing colors in theme settings

- components/03-organisms/site-header/_yds-site-header.scss
- Raise the site header's z-index from 2 to 10 to resolve a bug where the site menu appears incorrectly when banner blocks are present. This ensures proper stacking order and visual consistency.
> YSP-1142: RC: Site menu z-index

- components/02-molecules/cards/custom-card/_yds-custom-card.scss
- Added top, left, and right borders to `.custom-card__image-link`
- Other work completed in https://github.com/yalesites-org/yalesites-project/pull/1100
> YSP-926: Views: Card grid stroke outline

- components/01-atoms/date-time/yds-date-time.twig
- Add time formats that support same day with different times, and multiple days with times for view displays
- Other work completed in https://github.com/yalesites-org/atomic/pull/409
- Date work can really only be tested in Drupal at this time: https://github.com/yalesites-org/yalesites-project/pull/1101
> YSP-822: Add Event Time to Event Display Modes
