yalesites-org/component-library-twig

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md, components/00-tokens/effects/borders.twig, components/00-tokens/effects/cl-effects.scss, components/00-tokens/effects/effects.stories.js, components/00-tokens/effects/radii.twig, components/00-tokens/effects/shadows.twig, components/00-tokens/typography/_typography.scss, components/00-tokens/typography/body-styles.twig, components/00-tokens/typography/heading-styles.twig, package-lock.json, package.json
- Refactors heading/body style stories (in the dropdown)
- Adds docs to the style stories about using mixins
- Creates mixins 😄 
- Deletes unwanted docs about border radii
=> Fixes from demo review

components/00-tokens/colors/color-pairings.twig, components/00-tokens/typography/_typography.scss, components/01-atoms/buttons/_buttons.scss, components/01-atoms/buttons/button.stories.js, components/01-atoms/buttons/button.twig, components/01-atoms/links/_link.scss
- Defines button hover effects
=> fix: defined button hover effects

components/01-atoms/lists/_list.scss, components/01-atoms/lists/list.stories.js, components/01-atoms/lists/list.yml, components/01-atoms/typography/text/_text--examples.twig, components/01-atoms/typography/text/text.twig, components/01-atoms/typography/text/text.yml, components/01-atoms/typography/typography.stories.js
- Defines nested list styles
- Creates a text component
- Demos some basic inline text styles (using browser defaults - no custom styles)
=> 1) YALB-366: Text component

.github/workflows/visual-regression.yml, components/style.scss, package-lock.json, package.json
[YALB-62: Percy](https://yaleits.atlassian.net/browse/YALB-62)
- Configures Percy to run tests when a PR is switched from "Draft" to "Ready for review"
=> YALB-62: Percy

components/02-molecules/image/image.stories.js, components/02-molecules/molecules.scss, components/02-molecules/text-with-image/_text-with-image.scss, components/02-molecules/text-with-image/text-with-image.stories.js, components/02-molecules/text-with-image/text-with-image.twig, components/02-molecules/text-with-image/text-with-image.yml, components/05-page-examples/_intro-content-examples.twig, components/05-page-examples/news-article.twig, components/05-page-examples/page-examples.stories.js, package-lock.json
- Creates the Text with Image component
- Adds it as an option for the "Intro Content" on the example Standard Page
=> YALB-79: Text-with-image component

.github/workflows/release.yml, .npmignore, webpack/css.js, webpack/webpack.common.js
=> fix(YALB-253): build css and attempt to keep dist in package

.npmignore, package.json
=> fix(YALB-253): trying to include dist

components/02-molecules/menu/_menu-item.twig, components/02-molecules/menu/menu.twig
=> fix(YALB-253): adds conditional for Drupal and StoryBook

components/00-tokens/layout/_layout.scss, components/02-molecules/accordion/_accordion-item.twig, components/02-molecules/accordion/accordion.twig
=> fix(YALB-250): support nested components in accordion

.storybook/main.js, .storybook/preview.js, components/02-molecules/alert/_alert.scss, components/02-molecules/alert/alert.js, components/02-molecules/alert/alert.stories.js, components/02-molecules/alert/alert.twig
- Fixes Alert icon direction (for expanded/collapsed)
- Adds JS to remove old alert IDs from localStorage
=> YALB-489: Wire Alerts

components/00-tokens/layout/_layout.scss, components/02-molecules/page-title/page-title.twig, package-lock.json
- Updates site-gutter for larger breakpoints
- Sets the page-title back to 'max' width (to align with header/breadcrumbs)
=> YALB-396: Design Feedback

components/02-molecules/banner/cta/cta-banner.twig
=> refactor(YALB-521): simplify image/figure templates

components/00-tokens/layout/_layout.scss, components/01-atoms/images/image/_image.scss, components/01-atoms/images/image/figure.yml, components/02-molecules/menu/_menu-item.twig, components/03-organisms/layout/layout.stories.js, components/03-organisms/layout/two-column/_two-column--example.twig, components/03-organisms/layout/two-column/_two-column.scss, components/03-organisms/layout/two-column/two-column.twig, components/03-organisms/menu/breadcrumbs/breadcrumbs.stories.js, components/03-organisms/organisms.scss, components/05-page-examples/news-article.twig, components/05-page-examples/standard-pages/standard-page-with-sidebar.twig, components/05-page-examples/standard-pages/standard-page.stories.js, system.emulsify.json
- Creates a two-column layout
- Demos the two-column layout on an example page
=> YALB-429: Layout Paragraphs FE

webpack/loaders.js
=> fix: docs update to trigger a release

components/02-molecules/cards/reference-card/reference-card.twig
- Changes reference card heading to h3 by default
=> YALB-555: Event Item

README.md
=> docs: detail how to install cl locally for development

components/01-atoms/date-time/date-time.twig, components/02-molecules/cards/reference-card/_reference-card.scss, components/02-molecules/cards/reference-card/event/_event-format.twig, components/02-molecules/cards/reference-card/examples/_card--examples.twig, components/02-molecules/cards/reference-card/reference-card.js, components/02-molecules/cards/reference-card/reference-card.twig, components/03-organisms/card-collection/_card-collection.scss
- Tweaks the reference card and card collections based on wiring to Drupal
=> YALB-495: Wire event paragraphs

components/02-molecules/text-with-image/_text-with-image.scss
- updates the spacing for text with image molecule.
=> YALB-561: text with image spacing

package.json
- Adds the dist and image folders to the deployed storybook to fix missing icons etc.
=> YALB-620: Fix deployed storybook

.storybook/setupTwig.js, components/02-molecules/cards/reference-card/examples/_card--examples.twig, components/02-molecules/menu/_menu-item.twig, components/02-molecules/molecules.scss, components/02-molecules/pager/_pager.scss, components/02-molecules/pager/cl-pager.js, components/02-molecules/pager/pager-first-and-last.yml, components/02-molecules/pager/pager-first.yml, components/02-molecules/pager/pager-last.yml, components/02-molecules/pager/pager.stories.js, components/02-molecules/pager/pager.twig, components/02-molecules/pager/pager.yml, components/03-organisms/menu/primary-nav/primary-nav.yml, components/05-page-examples/events/_event-collection--example.twig, components/05-page-examples/events/event-grid.twig, components/05-page-examples/events/event-list.twig, components/05-page-examples/events/events.stories.js, system.emulsify.json
- Creates the initial Pagination component
- Creates Event Grid page (should have had this before)
- Creates Event List page including the pager at the bottom
=> YALB-78: Pagination

components/02-molecules/tabs/_tab-content.twig, components/02-molecules/tabs/_tab-label.twig, components/02-molecules/tabs/tabs.twig
=> YALB-106: refactor tabs to support drupal

components/03-organisms/menu/breadcrumbs/yds-breadcrumbs.twig
=> fix(YALB-635): fixed breadcrumbs length

components/02-molecules/cards/custom-card/_yds-custom-card.scss, components/02-molecules/cards/custom-card/custom-card.stories.js, components/02-molecules/cards/custom-card/custom-card.yml, components/02-molecules/cards/custom-card/yds-custom-card.js, components/02-molecules/cards/custom-card/yds-custom-card.twig, components/02-molecules/molecules.scss, components/03-organisms/custom-card-collection/_yds-custom-card-collection.scss, components/03-organisms/custom-card-collection/custom-card-collection.stories.js, components/03-organisms/custom-card-collection/yds-custom-card-collection.twig, components/03-organisms/organisms.scss, system.emulsify.json
- Adds a molecule of a custom card
- Adds an organism of a custom card collection
- Each has the ability to have images or not and is featured or not (Though in practice, featured will always have images, secondary images are optional)
=> YALB-101: Custom card molecule

components/02-molecules/accordion/_yds-accordion.scss
- Increases padding on accordion item button
=> YALB-649: Feedback: Update spacing on accordions

components/02-molecules/quick-links/_yds-quick-links--links.twig, components/02-molecules/quick-links/_yds-quick-links.scss, components/02-molecules/quick-links/yds-quick-links.twig, components/03-organisms/custom-card-collection/yds-custom-card-collection.twig
=> YALB-94: quick-links wiring

components/01-atoms/date-time/_yds-date-time.scss
- updates the date font for  events and news.
=> YALB-720: changes date font to uppercase capitals

components/03-organisms/menu/utility-nav/_utility-nav--menu.twig, components/03-organisms/menu/utility-nav/yds-utility-nav.twig
- Adds a search form to the utility navigation area
- NOTE: This requires [PR-115](https://github.com/yalesites-org/yalesites-project/pull/115) from yalesites-project and [PR-46](https://github.com/yalesites-org/atomic/pull/46) from atomic
=> YALB-700: Search Form

components/00-tokens/effects/_effects.scss, components/02-molecules/alert/_yds-alert.scss
=> YALB-510: Alerts: Fade away animation

components/00-tokens/typography/_typography.scss, components/01-atoms/date-time/_yds-date-time.scss, components/02-molecules/cards/reference-card/_yds-reference-card.scss, components/02-molecules/menu/_yds-menu.scss, components/02-molecules/meta/event-meta/_yds-event-meta.scss, components/03-organisms/menu/breadcrumbs/_yds-breadcrumbs.scss, package-lock.json
- All the tweaks from the ticket...
=> YALB-823: Type changes from printer

components/03-organisms/menu/primary-nav/_yds-primary-nav.scss
- fix: primary-nav__link--level-0:last-child padding right removal
=> YALB-696: Header navigation alignment

components/02-molecules/banner/action/_yds-action-banner.scss
- Adds a `:after` pseudo element to `&[data-component-theme='white']`
=> YALB-797 CTA Banner White BG Variation - bottom border

package-lock.json
- Updates the tokens to 1.18.0
=> YALB-765: max width for elements

components/02-molecules/menu/_yds-menu-item.twig, components/02-molecules/menu/yds-menu.twig, components/03-organisms/_list-mixins.scss, components/03-organisms/menu/primary-nav/_yds-primary-nav.scss, components/03-organisms/menu/primary-nav/primary-nav.stories.js, components/03-organisms/menu/primary-nav/primary-nav.yml, components/03-organisms/menu/primary-nav/yds-primary-nav.twig, components/03-organisms/site-header/site-header.stories.js, components/03-organisms/site-header/yds-site-header.twig, components/04-page-layouts/page-layouts.stories.js, components/05-page-examples/events/events.stories.js, components/05-page-examples/miscellaneous/miscellaneous-page.stories.js, components/05-page-examples/news/news.stories.js, components/05-page-examples/standard-pages/standard-page.stories.js, components/_settings/config.stories.js
- Adds `basic` menu variation
- Adjusts styles to be contextual based on `menu-variation` `mega` or `basic`
=> YALB-767 - Basic Nav Organism

components/00-tokens/layout/_layout.scss, components/03-organisms/site-header/_yds-site-header.scss
- Fix the border botom in the header in mobile version so that it extends to full width
=> YALB-824: Feedback: Small size header border shrink

components/02-molecules/molecules.scss, components/02-molecules/search-result/_yds-search-result.scss, components/02-molecules/search-result/breadcrumbs.yml, components/02-molecules/search-result/search-result.yml, components/02-molecules/search-result/yds-search-result.stories.js, components/02-molecules/search-result/yds-search-result.twig, components/03-organisms/component-wrapper/component-wrapper.stories.js, components/03-organisms/component-wrapper/yds-component-wrapper.twig, components/03-organisms/menu/breadcrumbs/_yds-breadcrumbs.scss, components/03-organisms/menu/breadcrumbs/yds-breadcrumbs.js, components/03-organisms/menu/breadcrumbs/yds-breadcrumbs.twig, components/03-organisms/menu/utility-nav/yds-utility-nav.twig
- Theming for search page and search results
- Adds components for search results and component wrapper (for wrapping things like views, title, etc)
=> YALB-96/600: Search Theming

components/02-molecules/embed/_yds-embed.scss, components/02-molecules/embed/yds-embed.twig
- fix: adjust embed markup and use twig block
=> YALB-462 - Embeds: Theming Elements

components/01-atoms/controls/text-link/_yds-text-link.scss, components/02-molecules/cards/reference-card/_yds-reference-card.scss, package-lock.json
- fix: update to lateset tokens
=> YALB-871 - Feedback: Printer's type changes

components/02-molecules/pull-quote/_yds-pull-quote.scss
- updates pull quote to use font size XL
(before)
(after)
=> YALB-399: Feedback: Update to Pull Quote

components/01-atoms/lists/yds-list.twig, components/02-molecules/accordion/yds-accordion.twig
=> Release (Hotfix)

components/02-molecules/tabs/yds-tabs.twig
- Remove custom theming for local tasks as we are no longer using this block.
=> YALB-820: Move local tasks

components/02-molecules/pull-quote/pull-quote.stories.js
- Renames the pull quote component to quote
=> YALB-970: Rename quote component

components/00-tokens/colors/cl-colors.scss, components/00-tokens/colors/color-global-theme-pairings.twig, components/01-atoms/controls/text-link/_yds-text-link.scss, components/02-molecules/cards/custom-card/_yds-custom-card.scss, components/03-organisms/custom-card-collection/custom-card-collection.stories.js, package-lock.json
- adds background top color on hover, animates the gradient
=> YALB-1162 - Cards: Custom cards style updates

components/03-organisms/menu/utility-nav/yds-utility-nav.twig, components/03-organisms/site-header/_site-header--secondary.twig, components/03-organisms/site-header/yds-site-header.twig
- Ensures unique ID's for all search form elements for accessibility
=> YALB-1325: Bug: Accessibility issues with Search

components/02-molecules/alert/yds-alert.twig, components/02-molecules/tabs/_yds-tabs.scss, components/02-molecules/wrapped-image/_yds-wrapped-image.scss, components/03-organisms/galleries/gallery.stories.js, components/03-organisms/galleries/media-grid/_yds-media-grid-modal.scss, components/03-organisms/galleries/media-grid/yds-media-grid-interactive.js, package-lock.json
- wrap `alert` in a `<section>` instead of a `<div>`
- add `aria-label="announcement"` to the alert component
- add `aria-label` to the interactive media gallery caption toggle button
- adjust bottom-margin on wrapped-image component to match top-margin, decreasing the margin between the bottom of the floated image and the paragraph below it.
---
---
https://github.com/yalesites-org/component-library-twig/assets/366413/4771a011-8a8f-41da-8738-1cce0b506320
---
https://github.com/yalesites-org/component-library-twig/assets/366413/03b405f7-373c-490b-970d-0404187a0deb
---
=> YALB-1581: Accessibility: Alert needs landmark and accessible name

components/02-molecules/cards/reference-card/_yds-reference-card.scss, components/02-molecules/cards/reference-card/reference-card.stories.js, components/02-molecules/cards/reference-card/yds-reference-card.twig, components/02-molecules/meta/event-meta/_yds-event-meta.scss, components/02-molecules/meta/event-meta/event-localist.yml, components/02-molecules/meta/event-meta/yds-event-meta-localist.twig
- Adds `stream_url` and `stream_embed_code` to Events
- Adds contextual styles to allow optional fields to expand/contract as needed
- Adds `reference_heading__prefix` to wire `event_title__prefix` for event reference cards
=> YSP-560: Localist: Update Event lists + default image updates

components/02-molecules/content-spotlight-portrait/_yds-content-spotlight-portrait.scss, components/02-molecules/text-with-image/_yds-text-with-image.scss, components/05-page-examples/standard-pages/standard-page-banner-spotlights.twig, components/05-page-examples/standard-pages/standard-page.stories.js
- For controls we track for 'first', 'last', or 'first-and-last' positioning, we adjust the top margin to be 0
=> YSP-569: V1.4.0 Spotlight in banner area has extra padding above

components/00-tokens/layout/yds-layout.js, components/03-organisms/site-header/yds-site-header.twig
Work also done in [Atomic](https://github.com/yalesites-org/atomic/pull/254).
- Default showing hamburger to always yes.
=> YSP-581: Mobile hamburger menu not showing up

package-lock.json
- Updates package-lock to bump tokens to 1.31.0
=> Bump Tokens to 1.31.0

components/02-molecules/meta/event-meta/event-localist.yml, components/02-molecules/meta/event-meta/yds-event-meta-localist.twig, package-lock.json
- Fixes Daylight Savings Time offset errors (when combined with yalesites-project PR)
=> Hotfix Release

components/02-molecules/search-result/_yds-search-result.scss, components/02-molecules/search-result/search-result.yml, components/02-molecules/search-result/yds-search-result.stories.js, components/02-molecules/search-result/yds-search-result.twig
Real work done in PR https://github.com/yalesites-org/component-library-twig/pull/398, however we cannot merge it due to CI issues.  Trying here for a successful build to merge.
=> JAKALA-Clone: Search page content filter

components/01-atoms/date-time/yds-date-time.twig, components/02-molecules/meta/event-meta/yds-event-meta-localist.twig, components/02-molecules/meta/event-meta/yds-event-meta.twig
- Remote spaces
- Replace am to a.m. and pm to p.m.
=> YSP-646: PRESIDENT: Event time display updates

package-lock.json, package.json
This fixes rate limit issues we experienced in github CI.
=> fix(semver): update semantic-version to latest release

components/01-atoms/typography/headings/yds-heading.twig, components/02-molecules/cards/reference-card/_yds-reference-card.scss, components/02-molecules/cards/reference-card/reference-card.stories.js, components/02-molecules/cards/reference-card/yds-reference-card.twig, components/03-organisms/card-collection/card-collection.stories.js
This work is dependent on the following other PRs--please review these as well:
- [YaleSites Project](https://github.com/yalesites-org/yalesites-project/pull/860)
- [Atomic](https://github.com/yalesites-org/atomic/pull/301)
- Added overlay text option to reference card SCSS for styling
- Updated reference card stories to include overlay text
- Modified reference card Twig template to render overlay text
- Overlay background matches global palette (slot-one)
=> YSP-769: Add "Pin to Top" visual indicator

components/01-atoms/forms/_yds-form.scss
- Fix apply button dangle (can only see on YaleSites platform)
- Fix mobile chosen drop down look and feel
=> v1.13.0 Feedback Changes 2

components/03-organisms/menu/breadcrumbs/yds-breadcrumbs.twig, components/03-organisms/site-in-this-section/_site-in-this-section.scss
- Adds the ability to always show breadcrumbs via a variable
=> IYY-335: Follow-ups on Book Module/Secondary Nav

components/03-organisms/menu/utility-nav/_yds-utility-nav.scss, components/03-organisms/menu/utility-nav/utility-nav-dropdown-menu.js, components/03-organisms/menu/utility-nav/utility-nav.stories.js, components/03-organisms/menu/utility-nav/yds-utility-nav--example.twig, components/03-organisms/menu/utility-nav/yds-utility-nav-example.twig
[IYY-375 : Dropdown scroll issue](https://app.clickup.com/t/36718269/IYY-375)
[IYY-383 : Utility dropdown color change](https://app.clickup.com/t/36718269/IYY-383)
- Remove unwanted horizontal scroll caused by utility dropdown
- Update utility dropdown button color
=> IYY-375 : Dropdown scroll issue

components/01-atoms/controls/cta/_yds-cta.scss, components/03-organisms/menu/secondary-nav/_yds-secondary-nav.scss, components/03-organisms/site-in-this-section/_site-in-this-section.scss
- Revert font size changes in content collection
- Fix contrast issues on `three` component theme on CTAs
=> 1.63.0 hotfix
